package constant

var MeanResponses = []string{
	"Well, well, look who just became the master of wrong answers.",
	"You must be a professional at being wrong by now.",
	"Is your brain on vacation, or are you naturally this clueless?",
	"Congratulations, you've managed to get it wrong again. Impressive consistency!",
	"I've seen better answers on the back of cereal boxes.",
	"It's almost impressive how wrong you can be.",
	"Keep trying. You'll get it right eventually, or not. It's not like it matters.",
	"Do you get lost in thought because it's unfamiliar territory?",
	"Wrong again. I'd suggest a GPS, but I don't think it could navigate your thoughts.",
	"They say practice makes perfect, but in your case, it seems to make perfectly wrong.",
	"Well, your answer wins the 'Most Creative Answer' award!",
	"Oops, not quite, but you've definitely got a unique perspective!",
	"That's a creative twist, but not quite what we were looking for.",
	"Incorrect, but you're thinking outside the box... and the circle... and the triangle.",
	"Hmmm, not quite, but your answer is like a surprise plot twist!",
	"Interesting choice! It's not the answer, but it's got style.",
	"Nope, but your answer is like a comedian's punchline - unexpected!",
	"Close, but not quite! You're dancing to the beat of your own quiz drum.",
	"Wrong answer, but your imagination is in full gear!",
	"That's not it, but you're on an adventure of your own making!",
	"Oops, not quite! You're like a detective who just found a donut instead of a clue.",
	"Almost there! Your answer is so close, it's practically on the same block.",
	"Not quite, but you're as determined as a squirrel trying to crack a nut.",
	"Close, but no cigar. You're the quiz version of a professional tango dancer - always a step away from perfection!",
	"Nice try! You're playing this quiz like a jazz musician - every note is a surprise.",
	"Incorrect, but your persistence is as admirable as a penguin waddling through a snowstorm.",
	"Wrong answer, but you've got the enthusiasm of a dog chasing its tail!",
	"You missed the bullseye, but you're throwing darts like a ninja with a sense of humor.",
	"Not quite, but you're on a rollercoaster of guesses, and it's a wild ride!",
	"Incorrect, but you're like a stand-up comedian testing new material. Keep the jokes coming!",
	"I'd say you're a few sandwiches short of a picnic, but that might be too generous.",
	"If stupidity were an Olympic event, you'd be a gold medalist.",
	"Your answers are like a broken record - annoying and always the same.",
	"Wrong again. It's almost like you're allergic to the right answer.",
	"Are you trying to be wrong, or does it just come naturally to you?",
	"You keep missing the mark like it's a full-time job.",
	"Your answers are so off, even GPS couldn't find them.",
	"If you had a dollar for every wrong answer, you'd be a millionaire by now.",
	"I'm starting to believe that 'incorrect' is your middle name.",
	"Your answers are like a bad horror movie: predictable and painful to watch.",
	"Wrong answers must be your comfort zone. You're certainly cozy there.",
	"You're consistently wrong, like a broken clock that's also missing hands.",
	"I'd say you're on fire, but it's more like a dumpster fire of answers.",
	"Keep it up, and you might become legendary for all the wrong reasons.",
	"A valiant attempt, but the answer's playing hard to get.",
	"Not the answer, but your creativity knows no bounds.",
	"Good effort, but it's like searching for a needle in a haystack.",
	"You're like a puzzle-solving maestro, just not this time.",
	"It's like you're allergic to correctness.",
	"I have to applaud your dedication to getting it wrong.",
	"Do you practice being this off, or does it come naturally?",
	"Wrong again, but at least you're consistent in your incompetence.",
	"Your answers are so far off, they should have their own zip code.",
	"If wrong answers were an art form, you'd be a master.",
	"You're like a riddle wrapped in an enigma of wrongness.",
	"I've seen better answers from a Magic 8-Ball.",
	"Wrong once more. You're setting records, just not the good kind.",
	"It's remarkable how you make wrong answers seem like a lifestyle choice.",
	"Your answers are like a comedy of errors, without the comedy part.",
	"I'm starting to wonder if you're secretly trying to sabotage yourself.",
	"Incorrect again, but keep it up, you're a pro at this.",
}
